name: base 
dependencies:
  - anaconda::numpy=2.2
  - conda-forge::matplotlib
  - anaconda::pyyaml
  - conda-forge::chess
  - conda-forge::lightning
  - conda-forge::tensorboard
  - conda-forge::chess
  - conda-forge::python-wget
  - anaconda::pip
  - pip:
      - fairscale

